### ISSUE TITLE
SetPosition don't work, CommandService typo

### ISSUE THREAD

**Issue by immago** [Zexuz/MPC-HC-CSharp-Api#2]
Services/CommandService.cs

Line 35
In set position method used Command.Volume enum.
I change Command.Volume to Command.Position but after that i received Filed status.

```
return await Execute(Command.Volume,info => IsInRange(info.PositionMillisec - 
```

UPD.
Also;
Line 117, Execute method: You forget to pass secondArg param
`var info = await GetResult(command, null);`

**Comment by Zexuz** [comment]
Thanks you for pointing out the enum mix-up and for providing a possible solution. 

I pushed a new NuGet version (1.1.1) and it should be available in the next couple minutes.
