### ISSUE TITLE
Cannot find the package from Bonsai

### ISSUE THREAD

**Issue by MIhidoype** [Zexuz/MPC-HC-CSharp-Api#4]
Hello,

I would like to use this package in Bonsai. I found it in 'Manage Packages' while using Bonsai from one computer, but not from another computer. Is there a way to add the package to Bonsai without installing it directly from Bonsai?

Thank you!

**Comment by Zexuz** [comment]
I don't know how Bonsai works, but if you can't install it from NuGet then I don't think I can help you. Maybe this is a question for StackOwerflow or the Bonsai community?
